# Generated by Django 5.0.6 on 2024-05-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabledata',
            name='detail',
        ),
        migrations.AddField(
            model_name='tabledata',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
