# Generated by Django 5.0.6 on 2024-06-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0004_userregistratione_downloadhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensitiveData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_field', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='userregistratione',
            name='categorie',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
