# Generated by Django 5.0.6 on 2024-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0005_marche_categorie_tabledata_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
