# Generated by Django 5.0.6 on 2024-06-28 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0010_alter_contactrequest_type_of_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactrequest',
            options={'verbose_name': 'Demande de Contact', 'verbose_name_plural': 'Demandes de Contact'},
        ),
        migrations.AlterModelOptions(
            name='downloadhistory',
            options={'verbose_name': 'Historique de téléchargement', 'verbose_name_plural': 'Historiques de téléchargement'},
        ),
        migrations.AlterModelOptions(
            name='marche',
            options={'verbose_name': 'Marché attribue', 'verbose_name_plural': 'Marchés attribues'},
        ),
        migrations.AlterModelOptions(
            name='newslettersubscription',
            options={'verbose_name': 'Abonnement AO', 'verbose_name_plural': 'Abonnements AO'},
        ),
        migrations.AlterModelOptions(
            name='tabledata',
            options={'verbose_name': 'Table AO', 'verbose_name_plural': 'Tables AO'},
        ),
        migrations.AlterModelOptions(
            name='userregistratione',
            options={'verbose_name': 'Inscription des utilisateurs', 'verbose_name_plural': 'Inscriptions des utilisateurs'},
        ),
    ]
