# Generated by Django 5.0.6 on 2024-07-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AO_app', '0011_alter_contactrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
